name: Tests CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        working-directory: ./src/Bacen.Dollar.Api.Client/
        run: dotnet restore
      - name: Build
        working-directory: ./src/Bacen.Dollar.Api.Client/
        run: dotnet build --no-restore
      - name: Unit Tests
        working-directory: ./tests/Bacen.Dollar.Api.Client.UnitTest/
        run: dotnet test
      - name: Integration Tests
        working-directory: ./tests/Bacen.Dollar.Api.Client.IntegrationTest/
        run: dotnet test
